# Generated by Django 4.2.6 on 2023-10-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_logininfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
